### ISSUE TITLE
mycat 1.4 疑似bug

### ISSUE THREAD

**Issue by charleslee89** [MyCATApache/Mycat-download#10]
childTable 设置autoIncrement，全局seq并没有起作用。1.3下是可以的。

**Comment by magicdoom** [comment]
<table name="ff"  primaryKey="ID" autoIncrement="true"  dataNode="dn$1-5" rule="sharding-by-murmur">
        <childTable name="child" joinKey="t_id"   autoIncrement="true"   primaryKey="ID"
        parentKey="id" />
        </table>

你参考下这个配置，是可以的

**Comment by charleslee89** [comment]
记录一下, 群里确认了是1.4的bug,@magicdoom 回复的时候 已经修复了
