### ISSUE TITLE
PHP PDO使用参数连接错误

### ISSUE THREAD

**Issue by cusele** [MyCATApache/Mycat-download#20]
//获取异常数据库
$conn_info=new PDO("mysql:host=127.0.0.1;port=8806;dbname=testdb","test","test",array(PDO::ATTR_ERRMODE => 2, PDO::ATTR_EMULATE_PREPARES => true));
PHP PDO连接MyCAT自从加了两个参数后就报错，导致laravel等使用PDO的加框架不能使用MyCAT

**Comment by funway** [comment]
请问这个问题解决了吗？

**Comment by ginnerpeace** [comment]
并没有, 这是一群做Java的人写的, 不一定会对其他语言进行友好地改进, 还是尝试kingshard吧
