### ISSUE TITLE
期待Mycat 实现自动offline复制不正常的slave和读写分离Read调度算法更丰富

### ISSUE THREAD

**Issue by hhl419** [MyCATApache/Mycat-download#21]
1. Mycat 目前版本都没有对slave  复制是否正常做check，自动发现并自动把复制不正常的slave offline掉，确保不会读到复制不正常的slave，期待这个功能加上。
2.读写分离这块没有对read 没有调度算法，目前看到的只有随机，比如说按照权重比设置几个slave的read的权重，还有根据连接数来调度slave 应该怎么读取？－－ 期待read 的调度算法更丰富

**Comment by cusele** [comment]
可以使用 <heartbeat>show slave status</heartbeat>来定义检查slave是否正常
