### ISSUE TITLE
com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION

### ISSUE THREAD

**Issue by wuchencm** [MyCATApache/Mycat-download#23]
SELECT id, num  FROM user 

[SQL]SELECT id, num  FROM user 

受影响的行: 0
时间: 0.008s

[Err] 1064 - com.alibaba.druid.sql.parser.ParserException: syntax error, expect RPAREN, actual ERROR DURATION

分片成功，select能查到数据，但是一直报这个error

**Comment by HashZhang** [comment]
你可能是用的navicat这种工具吧，会发一些其他查询语句过去。。你抓包看下
