### ISSUE TITLE
最基本的连个release包下载都有问题，还谈什么活跃？

### ISSUE THREAD

**Issue by t0791** [MyCATApache/Mycat-download#24]
https://github.com/MyCATApache/Mycat-download/tree/master/1.4-RELEASE
这下面的包能用的？下载完成后，解压就报错。请好好反省省吧

**Comment by HashZhang** [comment]
哪个系统的压缩包报错？

**Comment by t0791** [comment]
Mycat-server-1.4-release-20151019230038-linux.tar.gz
这个包就不能用

**Comment by t0791** [comment]
@HashZhang

**Comment by HashZhang** [comment]
我刚刚试了下，我这里在centOS6.5下解压没问题的。你重新下载试试看，或者拉一下源代码换到1.4 分支之后自己build下：
mvn clean package -Dmaven.test.skip

**Comment by t0791** [comment]
google浏览器直接下载，以及在suse11上下载解压都有问题，我是第一次在这里下载包出现这种情况

**Comment by t0791** [comment]
你是在这个页面上下载操作的吗
@HashZhang

**Comment by HashZhang** [comment]
是的哈，你最好再试试，应该是下载的问题，压缩包损坏。我下载后是没问题的

**Comment by t0791** [comment]
可以发我邮箱吗，很奇怪，刚用其他同事电脑下载都有问题。下载来的包都只有10K左右
邮箱： 360140186@qq.com
@HashZhang 
谢谢

**Comment by HashZhang** [comment]
好的，不过你得等晚上啦，公司不让发外部邮件^_^。如果有使用MyCat的想法和问题，多多交流哈。我也是MyCat的使用者。加我微信也可以2571656055

**Comment by t0791** [comment]
我的错，公司网络原因。谢谢专家点拨
