### ISSUE TITLE
DataNode能否定义到表一级？

### ISSUE THREAD

**Issue by PowerBin** [MyCATApache/Mycat-download#31]
使用中发现，DataNode的配置仅有：name、dataHost、database三个属性，没有表一级的配置选项，能够提供到trueTable(真实表)选项。

**Comment by Oloong** [comment]
是给表来指定DATANODE，而不是由DATANODE来指定表，个人认为把分区键从RULECONFIG配置中挪入TABLECONFIG中更迫切更实用，RULECONFIG只配通用的路由方法，而不具体某个表
