### ISSUE TITLE
PHP连接mysql 字符集乱码

### ISSUE THREAD

**Issue by lgshendy** [MyCATApache/Mycat-download#4]
经测试发现在1.4版本中 mycat 支持  set names utf8的写法  
不支持 set names ‘utf8’的写法
 建议支持  set names  ‘utf8’
 这种PHP的特殊写法

**Comment by netidol** [comment]
不需要set names ‘utf8’，我以前也是这样写，后来发现mycat已经默认配置是utf8了，把自己的类改一下吧
