### ISSUE TITLE
分片规则顺序会导致分片不一致

### ISSUE THREAD

**Issue by dasimple-zz** [MyCATApache/Mycat-download#7]
版本Mycat-server-1.4-RC-20150617220132-win.tar 
当使用rang-long-id 时，
配置autopartition-long.txt为
0-3=0
3-22=1
3分片在第1个分片上

配置autopartition-long.txt为
3-22=1
0-3=0
3分片在第2个分片上

**Comment by magicdoom** [comment]
这个是闭区间，请不要相互包含
0-3=0
4-22=1
